<?php
session_start();
require_once "../config/database.php";

// Check if user is logged in and is an admin
if(!isset($_SESSION["loggedin"]) || $_SESSION["loggedin"] !== true || $_SESSION["role"] !== "admin"){
    header("location: ../index.php");
    exit;
}

// Get the selected month
$month = isset($_POST['month']) ? $_POST['month'] : date('Y-m');

// Query to get priority-wise task statistics
$sql = "SELECT 
            tr.priority,
            COUNT(t.id) as total_tasks,
            SUM(CASE WHEN t.status = 'completed' THEN 1 ELSE 0 END) as completed_tasks,
            SUM(CASE WHEN t.status = 'pending' THEN 1 ELSE 0 END) as pending_tasks,
            SUM(CASE WHEN t.status = 'in_progress' THEN 1 ELSE 0 END) as in_progress_tasks,
            AVG(TIMESTAMPDIFF(HOUR, t.created_at, 
                CASE WHEN t.status = 'completed' THEN t.completed_at ELSE NOW() END)) as avg_time
        FROM tasks t
        JOIN task_requests tr ON t.request_id = tr.id
        WHERE DATE_FORMAT(t.created_at, '%Y-%m') = ?
        GROUP BY tr.priority
        ORDER BY FIELD(tr.priority, 'high', 'medium', 'low')";

if($stmt = mysqli_prepare($conn, $sql)){
    mysqli_stmt_bind_param($stmt, "s", $month);
    mysqli_stmt_execute($stmt);
    $result = mysqli_stmt_get_result($stmt);
    
    // Start HTML output
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Priority-wise Task Report - <?php echo date('F Y', strtotime($month)); ?></title>
        
        <!-- Include the same CSS as used in the main application -->
        <link href="../vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        <link href="../css/sb-admin-2.min.css" rel="stylesheet">
        <link href="../css/custom.css" rel="stylesheet">
        <link href="../vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
        
        <style>
            @media print {
                .no-print {
                    display: none;
                }
            }
            .priority-badge {
                display: inline-block;
                padding: 4px 8px;
                border-radius: 4px;
                color: white;
                font-weight: 600;
            }
            .priority-high {
                background-color: #e74a3b;
            }
            .priority-medium {
                background-color: #f6c23e;
                color: #5a5c69;
            }
            .priority-low {
                background-color: #1cc88a;
            }
            .priority-normal {
                background-color: #36b9cc;
            }
            .report-container {
                max-width: 1200px;
                margin: 0 auto;
                padding: 20px;
            }
        </style>
    </head>
    <body class="bg-gradient-light">
        <div class="report-container">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h2 class="text-primary">Priority-wise Task Report</h2>
                <div class="no-print">
                    <button onclick="window.print()" class="btn btn-primary shadow-sm">
                        <i class="fas fa-download fa-sm text-white-50"></i> Print Report
                    </button>
                    <a href="../index.php" class="btn btn-secondary shadow-sm">
                        <i class="fas fa-arrow-left fa-sm text-white-50"></i> Back to Dashboard
                    </a>
                </div>
            </div>
            
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Report Information</h6>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <p><strong>Report Period:</strong> <?php echo date('F Y', strtotime($month)); ?></p>
                        </div>
                        <div class="col-md-4">
                            <p><strong>Generated On:</strong> <?php echo date('F j, Y g:i A'); ?></p>
                        </div>
                        <div class="col-md-4">
                            <p><strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['username']); ?></p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Priority Summary Cards -->
            <div class="row mb-4">
                <?php
                // Reset result pointer
                mysqli_data_seek($result, 0);
                
                // Priority icon mapping
                $priority_icons = [
                    'high' => 'fa-exclamation-circle',
                    'medium' => 'fa-exclamation',
                    'low' => 'fa-arrow-down',
                    'normal' => 'fa-equals'
                ];
                
                // Priority card color mapping
                $priority_colors = [
                    'high' => 'danger',
                    'medium' => 'warning',
                    'low' => 'success',
                    'normal' => 'info'
                ];
                
                while($row = mysqli_fetch_assoc($result)){
                    // Default icon and color for unknown priority
                    $icon = 'fa-circle';
                    $color = 'secondary';
                    
                    // Set icon and color based on priority
                    if(isset($priority_icons[$row['priority']])) {
                        $icon = $priority_icons[$row['priority']];
                    }
                    
                    if(isset($priority_colors[$row['priority']])) {
                        $color = $priority_colors[$row['priority']];
                    }
                    
                    $completion_rate = $row['total_tasks'] > 0 ? 
                        round(($row['completed_tasks'] / $row['total_tasks']) * 100, 1) : 0;
                    ?>
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-<?php echo $color; ?> shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-<?php echo $color; ?> text-uppercase mb-1">
                                            <?php echo ucfirst($row['priority']); ?> Priority
                                        </div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800"><?php echo $row['total_tasks']; ?> Tasks</div>
                                        <div class="mt-2 small">
                                            Completion: <?php echo $completion_rate; ?>%
                                            <div class="progress progress-sm">
                                                <div class="progress-bar bg-<?php echo $color; ?>" 
                                                     role="progressbar" 
                                                     style="width: <?php echo $completion_rate; ?>%"></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fas <?php echo $icon; ?> fa-2x text-gray-300"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Priority Distribution</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Priority</th>
                                    <th>Total Tasks</th>
                                    <th>Completed</th>
                                    <th>Pending</th>
                                    <th>In Progress</th>
                                    <th>Completion Rate</th>
                                    <th>Avg. Time (hours)</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                $total_tasks = 0;
                                $total_completed = 0;
                                $total_pending = 0;
                                $total_in_progress = 0;
                                $total_completion_time = 0;
                                $priority_count = 0;
                                
                                // Reset result pointer
                                mysqli_data_seek($result, 0);
                                
                                while($row = mysqli_fetch_assoc($result)){
                                    $total_tasks += $row['total_tasks'];
                                    $total_completed += $row['completed_tasks'];
                                    $total_pending += $row['pending_tasks'];
                                    $total_in_progress += $row['in_progress_tasks'];
                                    
                                    $completion_rate = $row['total_tasks'] > 0 ? 
                                        round(($row['completed_tasks'] / $row['total_tasks']) * 100, 2) : 0;
                                    
                                    if($row['avg_time'] !== null){
                                        $total_completion_time += $row['avg_time'];
                                        $priority_count++;
                                    }
                                    
                                    // Determine badge class based on priority
                                    $badge_class = 'priority-' . strtolower($row['priority']);
                                    ?>
                                    <tr>
                                        <td>
                                            <span class="priority-badge <?php echo $badge_class; ?>">
                                                <?php echo ucfirst($row['priority']); ?>
                                            </span>
                                        </td>
                                        <td><?php echo $row['total_tasks']; ?></td>
                                        <td><?php echo $row['completed_tasks']; ?></td>
                                        <td><?php echo $row['pending_tasks']; ?></td>
                                        <td><?php echo $row['in_progress_tasks']; ?></td>
                                        <td>
                                            <div class="progress">
                                                <div class="progress-bar bg-success" role="progressbar" 
                                                     style="width: <?php echo $completion_rate; ?>%" 
                                                     aria-valuenow="<?php echo $completion_rate; ?>" 
                                                     aria-valuemin="0" aria-valuemax="100">
                                                    <?php echo $completion_rate; ?>%
                                                </div>
                                            </div>
                                        </td>
                                        <td><?php echo $row['avg_time'] ? round($row['avg_time'], 2) : '-'; ?></td>
                                    </tr>
                                    <?php
                                }
                                
                                $overall_completion_rate = $total_tasks > 0 ? 
                                    round(($total_completed / $total_tasks) * 100, 2) : 0;
                                $avg_completion_time = $priority_count > 0 ? 
                                    round($total_completion_time / $priority_count, 2) : 0;
                                ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Total/Average</th>
                                    <th><?php echo $total_tasks; ?></th>
                                    <th><?php echo $total_completed; ?></th>
                                    <th><?php echo $total_pending; ?></th>
                                    <th><?php echo $total_in_progress; ?></th>
                                    <th>
                                        <div class="progress">
                                            <div class="progress-bar bg-success" role="progressbar" 
                                                 style="width: <?php echo $overall_completion_rate; ?>%" 
                                                 aria-valuenow="<?php echo $overall_completion_rate; ?>" 
                                                 aria-valuemin="0" aria-valuemax="100">
                                                <?php echo $overall_completion_rate; ?>%
                                            </div>
                                        </div>
                                    </th>
                                    <th><?php echo $avg_completion_time; ?></th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>

            <!-- Notes Section -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Notes</h6>
                </div>
                <div class="card-body">
                    <ul>
                        <li>This report shows task distribution across priorities for <?php echo date('F Y', strtotime($month)); ?>.</li>
                        <li>Completion rate is calculated as (completed tasks / total tasks) × 100%.</li>
                        <li>Average time is measured in hours from task creation to completion.</li>
                        <li>Tasks with no set priority default to "Normal" priority.</li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Bootstrap core JavaScript-->
        <script src="../vendor/jquery/jquery.min.js"></script>
        <script src="../vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

        <!-- Core plugin JavaScript-->
        <script src="../vendor/jquery-easing/jquery.easing.min.js"></script>

        <!-- Custom scripts for all pages-->
        <script src="../js/sb-admin-2.min.js"></script>

        <!-- Page level plugins -->
        <script src="../vendor/datatables/jquery.dataTables.min.js"></script>
        <script src="../vendor/datatables/dataTables.bootstrap4.min.js"></script>

        <!-- Initialize DataTables -->
        <script>
        $(document).ready(function() {
            $('#dataTable').DataTable({
                "order": [[1, "desc"]], // Sort by tasks column by default
                "pageLength": 10,
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]]
            });
        });
        </script>
    </body>
    </html>
    <?php
    mysqli_stmt_close($stmt);
} else {
    echo "Error preparing statement: " . mysqli_error($conn);
}

// Connection is already closed by shutdown function
?> 