<?php
session_start();
require_once "../config/database.php";

// Check if user is logged in and is an admin
if(!isset($_SESSION["loggedin"]) || $_SESSION["loggedin"] !== true || $_SESSION["role"] !== "admin"){
    header("location: ../index.php");
    exit;
}

// Get the selected month
$month = isset($_POST['month']) ? $_POST['month'] : date('Y-m');

// Query to get status-wise task statistics
$sql = "SELECT 
            t.status,
            COUNT(t.id) as total_tasks,
            AVG(TIMESTAMPDIFF(HOUR, t.created_at, 
                CASE WHEN t.status = 'completed' THEN t.completed_at ELSE NOW() END)) as avg_time,
            COUNT(DISTINCT t.assigned_to) as unique_assignees,
            COUNT(DISTINCT tr.department_id) as unique_departments
        FROM tasks t
        JOIN task_requests tr ON t.request_id = tr.id
        WHERE DATE_FORMAT(t.created_at, '%Y-%m') = ?
        GROUP BY t.status
        ORDER BY FIELD(t.status, 'completed', 'in_progress', 'pending')";

if($stmt = mysqli_prepare($conn, $sql)){
    mysqli_stmt_bind_param($stmt, "s", $month);
    mysqli_stmt_execute($stmt);
    $result = mysqli_stmt_get_result($stmt);
    
    // Start HTML output
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Status-wise Task Report - <?php echo date('F Y', strtotime($month)); ?></title>
        
        <!-- Include the same CSS as used in the main application -->
        <link href="../vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        <link href="../css/sb-admin-2.min.css" rel="stylesheet">
        <link href="../css/custom.css" rel="stylesheet">
        <link href="../vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
        
        <style>
            @media print {
                .no-print {
                    display: none;
                }
            }
            .status-badge {
                display: inline-block;
                padding: 4px 8px;
                border-radius: 4px;
                color: white;
                font-weight: 600;
            }
            .status-completed {
                background-color: #28a745;
            }
            .status-in_progress {
                background-color: #17a2b8;
            }
            .status-pending {
                background-color: #ffc107;
                color: #212529;
            }
            .status-pending_confirmation {
                background-color: #6c757d;
            }
            .status-rejected {
                background-color: #dc3545;
            }
            .report-container {
                max-width: 1200px;
                margin: 0 auto;
                padding: 20px;
            }
        </style>
    </head>
    <body class="bg-gradient-light">
        <div class="report-container">
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h2 class="text-primary">Status-wise Task Report</h2>
                <div class="no-print">
                    <button onclick="window.print()" class="btn btn-primary shadow-sm">
                        <i class="fas fa-download fa-sm text-white-50"></i> Print Report
                    </button>
                    <a href="../index.php" class="btn btn-secondary shadow-sm">
                        <i class="fas fa-arrow-left fa-sm text-white-50"></i> Back to Dashboard
                    </a>
                </div>
            </div>
            
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Report Information</h6>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <p><strong>Report Period:</strong> <?php echo date('F Y', strtotime($month)); ?></p>
                        </div>
                        <div class="col-md-4">
                            <p><strong>Generated On:</strong> <?php echo date('F j, Y g:i A'); ?></p>
                        </div>
                        <div class="col-md-4">
                            <p><strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['username']); ?></p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row mb-4">
                <?php
                $total_tasks = 0;
                $statuses = array();
                
                // First pass to get totals
                mysqli_data_seek($result, 0);
                while($row = mysqli_fetch_assoc($result)) {
                    $total_tasks += $row['total_tasks'];
                    $statuses[$row['status']] = $row;
                }
                
                // Status cards with proper Bootstrap classes for SB Admin 2
                $status_classes = [
                    'completed' => 'success',
                    'in_progress' => 'info',
                    'pending' => 'warning',
                    'pending_confirmation' => 'secondary',
                    'rejected' => 'danger'
                ];
                
                $status_icons = [
                    'completed' => 'fa-check-circle',
                    'in_progress' => 'fa-sync',
                    'pending' => 'fa-clock',
                    'pending_confirmation' => 'fa-hourglass-half',
                    'rejected' => 'fa-times-circle'
                ];
                
                foreach($status_classes as $status => $color_class) {
                    $count = isset($statuses[$status]) ? $statuses[$status]['total_tasks'] : 0;
                    $percentage = $total_tasks > 0 ? round(($count / $total_tasks) * 100, 1) : 0;
                    ?>
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-<?php echo $color_class; ?> shadow h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-<?php echo $color_class; ?> text-uppercase mb-1">
                                            <?php echo str_replace('_', ' ', ucfirst($status)); ?>
                                        </div>
                                        <div class="h5 mb-0 font-weight-bold text-gray-800"><?php echo $count; ?> Tasks (<?php echo $percentage; ?>%)</div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fas <?php echo $status_icons[$status]; ?> fa-2x text-gray-300"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Status Distribution</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Status</th>
                                    <th>Tasks</th>
                                    <th>% of Total</th>
                                    <th>Avg. Time (hours)</th>
                                    <th>Unique Assignees</th>
                                    <th>Unique Departments</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                mysqli_data_seek($result, 0);
                                while($row = mysqli_fetch_assoc($result)){
                                    $percentage = $total_tasks > 0 ? round(($row['total_tasks'] / $total_tasks) * 100, 2) : 0;
                                    ?>
                                    <tr>
                                        <td>
                                            <span class="status-badge status-<?php echo $row['status']; ?>">
                                                <?php echo str_replace('_', ' ', ucfirst($row['status'])); ?>
                                            </span>
                                        </td>
                                        <td><?php echo $row['total_tasks']; ?></td>
                                        <td><?php echo $percentage; ?>%</td>
                                        <td><?php echo round($row['avg_time'], 2); ?></td>
                                        <td><?php echo $row['unique_assignees']; ?></td>
                                        <td><?php echo $row['unique_departments']; ?></td>
                                    </tr>
                                    <?php
                                }
                                ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>Total</th>
                                    <th><?php echo $total_tasks; ?></th>
                                    <th>100%</th>
                                    <th>-</th>
                                    <th>-</th>
                                    <th>-</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>

            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Notes</h6>
                </div>
                <div class="card-body">
                    <ul>
                        <li>This report shows task distribution by status for <?php echo date('F Y', strtotime($month)); ?>.</li>
                        <li>Average time is measured in hours from task creation to completion or current time for ongoing tasks.</li>
                        <li>Tasks with no status are not included in this report.</li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- Bootstrap core JavaScript-->
        <script src="../vendor/jquery/jquery.min.js"></script>
        <script src="../vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

        <!-- Core plugin JavaScript-->
        <script src="../vendor/jquery-easing/jquery.easing.min.js"></script>

        <!-- Custom scripts for all pages-->
        <script src="../js/sb-admin-2.min.js"></script>

        <!-- Page level plugins -->
        <script src="../vendor/datatables/jquery.dataTables.min.js"></script>
        <script src="../vendor/datatables/dataTables.bootstrap4.min.js"></script>

        <!-- Initialize DataTables -->
        <script>
        $(document).ready(function() {
            $('#dataTable').DataTable({
                "order": [[1, "desc"]], // Sort by tasks column by default
                "pageLength": 10,
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]]
            });
        });
        </script>
    </body>
    </html>
    <?php
    mysqli_stmt_close($stmt);
} else {
    echo "Error preparing statement: " . mysqli_error($conn);
}

// Connection is already closed by shutdown function
?> 